---
http_interactions:
- request:
    method: get
    uri: https://hostname/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - default
      Authorization:
      - Bearer token
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Wed, 23 Nov 2016 09:01:23 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=845a8df11f6e66df3c0c6b2d72601068; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Wed, 23 Nov 2016 09:01:23 GMT
- request:
    method: get
    uri: https://hostname/hawkular/metrics/counters/registry%2Fd0feee6a-ab59-11e6-a7ff-001a4a2314d5%2Fcpu%2Fusage/stats/?bucketDuration=20s&start=1468235823000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - default
      Authorization:
      - Bearer token
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Wed, 23 Nov 2016 09:01:24 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=845a8df11f6e66df3c0c6b2d72601068; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1468235823000,"end":1468235843000,"empty":true},{"start":1479891683000,"end":1479891703000,"empty":true}]'
    http_version: 
  recorded_at: Wed, 23 Nov 2016 09:01:27 GMT
- request:
    method: get
    uri: https://hostname/hawkular/metrics/gauges/registry%2Fd0feee6a-ab59-11e6-a7ff-001a4a2314d5%2Fmemory%2Fusage/stats/?bucketDuration=20s&start=1468235843000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - default
      Authorization:
      - Bearer token
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Wed, 23 Nov 2016 09:01:31 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=845a8df11f6e66df3c0c6b2d72601068; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1468235843000,"end":1468235863000,"empty":true},{"start":1479891683000,"end":1479891703000,"empty":true}]'
    http_version: 
  recorded_at: Wed, 23 Nov 2016 09:01:33 GMT
recorded_with: VCR 3.0.3
