---
http_interactions:
- request:
    method: get
    uri: https://hostname/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer token
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Wed, 23 Nov 2016 09:01:41 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=845a8df11f6e66df3c0c6b2d72601068; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Wed, 23 Nov 2016 09:01:41 GMT
- request:
    method: get
    uri: https://hostname/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer token
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Wed, 23 Nov 2016 09:01:41 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=845a8df11f6e66df3c0c6b2d72601068; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Wed, 23 Nov 2016 09:01:41 GMT
recorded_with: VCR 3.0.3
